spring:
  datasource:
    url: jdbc:h2:file:/src/main/resources/db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
  spring:
    flyway:
      enabled: true
      locations: classpath:/src/main/resources/db/migration
